### ISSUE TITLE
Binding the super key to open the whisker-menu prevents the use of the super key for any other shortcut

### ISSUE THREAD

**Issue by pedrohqb** [endeavouros-team/endeavouros-xfce4-theming#1]
As the title says, binding the super key to open the whisker-menu prevents the use of the super key for any other shortcut.

It seems to be an old XFCE bug. It does happen because the whisker-menu opens when the super key is pressed, not when it is released.

For example, xfwm default shortcuts won't work if the super key is already set for something else.

As a solution, I used ksuperkey, which is present in the AUR. Using that application, the whisker men will only open when the super key is released. It seems that using xfce-superkey is also possible (as does MX Linux - check it out: https://github.com/MX-Linux/xfce-superkey)

I think that, as default, EndeavourOS should come without any keyboard key set to open the whisker menu, in order to not have any broken features out-of-the-box. Nonetheless, would be great having an wiki article teaching how to set up the super key to open the whisker menu.

**Comment by killajoe** [comment]
thanks for commenting on this, i do already bring this up on dev communications, so we will work on this.

**Comment by killajoe** [comment]
https://github.com/endeavouros-team/endeavouros-xfce4-theming/commit/639ecec23d2a416a4c0f0d84089f086bdd252785
