### ISSUE TITLE
Padding in completely unrelated GTK apps 

### ISSUE THREAD

**Issue by sliva0** [endeavouros-team/endeavouros-xfce4-theming#10]
Recently I installed [Terminator](https://gnome-terminator.org) app and was surprised to find weird borders around all terminals.
![image](https://github.com/endeavouros-team/endeavouros-xfce4-theming/assets/48382801/28e38a2d-b9f7-47d0-88ef-cf789d58547d)

After some investigation, I found these lines in my `~/.config/gtk-3.0/gtk.css`:
```css
VteTerminal, vte-terminal {
    padding: 13px;
}
```
which came from this repository.

I can't think of any good reasons to set some generic style adjustments by default in the system, so please change it to more application-specific tags.

The same issue is also present in the GTK4 CSS file in this repository and the GTK3 CSS file in [i3-setup](https://github.com/endeavouros-team/endeavouros-i3wm-setup/blob/5557b6876b49cab2853c314ed8490943cbb25f10/etc/skel/.config/gtk-3.0/gtk.css) repo.

**Comment by sliva0** [comment]
A more explicit example of unnatural borders with vim:
![image](https://github.com/endeavouros-team/endeavouros-xfce4-theming/assets/48382801/840cb162-228f-4667-bd10-5a0e390d05e1)

**Comment by killajoe** [comment]
The padding was added to fix an issue with xfce4-terminal, what is the default terminal in both xfce4 and i3 setups. 
But you are right that it could be removed to provide a more generic default.

**Comment by sliva0** [comment]
I looked into GTK inspector and there is a specific xfce4-terminal CSS ID, so you can specify it, then the patch applies only to the targeted app:
```
#xfce4-terminal-notebook vte-terminal {
    padding: 13px;
}
```
![image](https://github.com/endeavouros-team/endeavouros-xfce4-theming/assets/48382801/cd92fa02-a659-44dc-bc7d-5efcbd152e9e)

**Comment by killajoe** [comment]
Still will check if we can remove it .. it was a long time ago added may the issue is changed and the tag unneeded

**Comment by killajoe** [comment]
Just checked, and
![Bildschirmfoto_2024-06-11_12-01-51](https://github.com/endeavouros-team/endeavouros-xfce4-theming/assets/16797647/f50b9118-e491-44bc-92df-a66932beae7e)
 it simply looks bad there is no padding at all without adding some:

**Comment by killajoe** [comment]
https://github.com/endeavouros-team/endeavouros-xfce4-theming/commit/dc6a7f259956322050857e212dae85af25310ab8

**Comment by killajoe** [comment]
resolved
